name: Documenter
on:
    push:
      branches: [master]
      tags: [v*]
    pull_request:

jobs:
    Documenter:
      name: Documentation
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install HolyLab Registry
          run: julia -e 'using Pkg; Pkg.Registry.add([RegistrySpec(name="General"),RegistrySpec(url="https://github.com/HolyLab/HolyLabRegistry")]);'
        - uses: julia-actions/julia-buildpkg@latest
        - uses: julia-actions/julia-docdeploy@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
